# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: amps
  - /task: multiclass_classification
  - /optimizer: adamw
  - /scheduler: plateau
  - /callbacks: [base, checkpoint, stopping]

train:
  # monitor: val/accuracy # Needed for plateau scheduler
  monitor: val/loss
  mode: min

encoder: id

# we need this for classification!
decoder:
  _name_: sequence
  mode: pool
