_name_: amps
dataset_name: amps
dest_path: null
max_length: 3200
d_output: 2
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.max_length}
__l_max: ${.max_length}
shuffle: true  # set this as default!
