_name_: plantsgenomic
dataset_name: plantsgenomic
max_length: 6400
tokenizer_name: char
add_eos: True
batch_size: 8 # per GPU
# batch_size_eval: ${eval:${.batch_size} * 2}
num_workers: 4  # For preprocessing only
shuffle: True
pin_memory: True
__train_len: ${.max_length}
__l_max: ${.max_length}
# use_padding: True
# padding_side: 'left'
# rc_aug: False
# csv_file: null
